"""كتالوج أنواع أدلة الاعتماد — المرحلة أ (هـ-3)."""

from __future__ import annotations

LINK_MODE_LABELS = {
    "auto": "ربط آلي",
    "hybrid": "هجين",
    "manual": "يدوي",
    "evidence": "شاهد",
}

EVIDENCE_CATEGORY_LABELS = {
    "survey": "استبيان (من المنظومة)",
    "minutes": "محاضر اجتماعات",
    "policy": "لوائح وسياسات",
    "report": "تقارير نظام",
    "file": "ملف / مرفق",
    "system": "بيانات نظام",
    "reference": "مستند مرجعي",
}

FULFILLMENT_STATUS_LABELS = {
    "met": "مكتمل",
    "partial": "جزئي",
    "missing": "ناقص",
    "not_applicable": "غير مطبّق",
}

# (code, title_ar, description_ar, category, source_module, source_ref, is_system, sort_order)
DEFAULT_EVIDENCE_TYPES: list[tuple] = [
    (
        "survey_student_course",
        "استبيان تقييم المقرر",
        "نتائج تقييم المقرر من الطلبة.",
        "survey",
        "multi_surveys",
        "student_course",
        1,
        10,
    ),
    (
        "survey_student_services",
        "استبيان رضا الطلبة — الشؤون والخدمات",
        "لقطة استبيان خدمات الطلبة.",
        "survey",
        "multi_surveys",
        "student_services",
        1,
        20,
    ),
    (
        "survey_student_facilities",
        "استبيان رضا الطلبة — المرافق",
        "لقطة استبيان المرافق والبنية التحتية.",
        "survey",
        "multi_surveys",
        "student_facilities",
        1,
        30,
    ),
    (
        "survey_faculty_hod",
        "استبيان أعضاء هيئة التدريس — رئيس القسم",
        "آراء الأساتذة حول القيادة والسياسات.",
        "survey",
        "multi_surveys",
        "faculty_hod",
        1,
        40,
    ),
    (
        "survey_faculty_dean",
        "استبيان أعضاء هيئة التدريس — الإدارة",
        "آراء الأساتذة حول الحوكمة والموارد.",
        "survey",
        "multi_surveys",
        "faculty_dean",
        1,
        50,
    ),
    (
        "survey_faculty_educational",
        "استبيان العملية التعليمية",
        "آراء الأساتذة حول التقويم والإقفال ومخرجات التعلم.",
        "survey",
        "multi_surveys",
        "faculty_educational_process",
        1,
        60,
    ),
    (
        "survey_supervisor_advising",
        "استبيان المشرف الأكاديمي — الإرشاد",
        "جودة الإرشاد والمتابعة.",
        "survey",
        "multi_surveys",
        "supervisor_advising",
        1,
        70,
    ),
    (
        "survey_staff_workplace",
        "استبيان رضا الموظفين",
        "بيئة العمل والخدمات الإدارية.",
        "survey",
        "multi_surveys",
        "staff_workplace",
        1,
        80,
    ),
    (
        "survey_alumni",
        "استبيان الخريجين",
        "آراء الخريجين في جودة التعليم والجاهزية المهنية.",
        "survey",
        "multi_surveys",
        "alumni",
        1,
        85,
    ),
    (
        "survey_employer",
        "استبيان جهة العمل",
        "استشارة القطاع في الخطة الاستراتيجية ومخرجات التعلم.",
        "survey",
        "multi_surveys",
        "employer_strategic",
        1,
        86,
    ),
    (
        "minutes_qa_committee",
        "محاضر لجنة ضمان الجودة",
        "محاضر اجتماعات لجنة الجودة/الاعتماد.",
        "minutes",
        "",
        "",
        0,
        90,
    ),
    (
        "minutes_governance",
        "محاضر مجالس ولجان الحوكمة",
        "مجلس الكلية، مجالس الأقسام، لجان دائمة.",
        "minutes",
        "",
        "",
        0,
        100,
    ),
    (
        "policy_department",
        "لوائح وسياسات معتمدة",
        "سياسات الأقسام المعتمدة في النظام.",
        "policy",
        "department_policies",
        "approved",
        1,
        110,
    ),
    (
        "college_identity_docs",
        "وثائق الرؤية والرسالة والخطة",
        "هوية الكلية المعتمدة.",
        "system",
        "college_identity",
        "profile",
        1,
        120,
    ),
    (
        "course_closure_reports",
        "تقارير إقفال المقررات",
        "تقارير إقفال الشعب للفصل.",
        "report",
        "course_closure",
        "reports",
        1,
        130,
    ),
    (
        "instructor_qualifications",
        "مؤهلات هيئة التدريس",
        "نسب المؤهلات من سجل الأساتذة.",
        "system",
        "accreditation_metrics",
        "HR-01-1",
        1,
        140,
    ),
    (
        "enrollment_graduation_metrics",
        "مؤشرات التسجيل والتخرج",
        "بيانات الطلبة والتخرج.",
        "system",
        "accreditation_metrics",
        "SS-02-1",
        1,
        150,
    ),
    (
        "quality_metrics_snapshot",
        "لقطة مؤشرات الجودة",
        "لقطات دورية من لوحة الجودة.",
        "system",
        "quality_metrics",
        "snapshots",
        1,
        160,
    ),
    (
        "manual_infrastructure",
        "تقييم البنية التحتية (إدخال يدوي)",
        "إدخال من تبويب الإدخال اليدوي.",
        "system",
        "accreditation_manual",
        "facilities_rating",
        1,
        170,
    ),
    (
        "manual_governance",
        "إدخال حوكمة ولجان",
        "اجتماعات وسياسات من الإدخال اليدوي.",
        "system",
        "accreditation_manual",
        "governance",
        1,
        180,
    ),
    (
        "generic_file_upload",
        "ملف داعم عام",
        "رفع ملف أو رابط يدوي للمؤشر.",
        "file",
        "",
        "",
        0,
        190,
    ),
    (
        "self_study_report",
        "تقرير الدراسة الذاتية",
        "وثيقة الدراسة الذاتية للاعتماد.",
        "reference",
        "accreditation_evidence",
        "self_study",
        0,
        200,
    ),
    (
        "standards_guide_pdf",
        "دليل معايير المركز",
        "نسخة معتمدة من دليل المعايير.",
        "reference",
        "accreditation_evidence",
        "standards_pdf",
        0,
        210,
    ),
]

# ربط استبيانات الكتالوج الداخلي 2026.1 (من SURVEY_ACCREDITATION_MAP)
SURVEY_TEMPLATE_TO_EVIDENCE_TYPE = {
    "student_course": "survey_student_course",
    "student_services": "survey_student_services",
    "student_facilities": "survey_student_facilities",
    "faculty_hod": "survey_faculty_hod",
    "faculty_dean": "survey_faculty_dean",
    "faculty_educational_process": "survey_faculty_educational",
    "supervisor_advising": "survey_supervisor_advising",
    "supervisor_coordination": "survey_supervisor_advising",
    "staff_workplace": "survey_staff_workplace",
    "staff_student_services": "survey_student_services",
    "alumni": "survey_alumni",
    "employer_strategic": "survey_employer",
}

# قواعد بالكلمات المفتاحية في نص المؤشر (لكتالوجات المركز)
KEYWORD_EVIDENCE_RULES: list[tuple[tuple[str, ...], str, str]] = [
    (("استطلاع", "آراء"), "survey_student_services", "evidence"),
    (("استبيان",), "survey_student_course", "evidence"),
    (("محضر",), "minutes_qa_committee", "evidence"),
    (("اجتماع", "لجنة"), "minutes_qa_committee", "evidence"),
    (("لائحة",), "policy_department", "evidence"),
    (("سياسة",), "policy_department", "evidence"),
    (("إقفال", "مقرر"), "course_closure_reports", "evidence"),
    (("رؤية", "رسالة"), "college_identity_docs", "evidence"),
    (("خطة", "إستراتيج"), "college_identity_docs", "evidence"),
    (("مؤهل", "هيئة التدريس"), "instructor_qualifications", "auto"),
    (("تخرج",), "enrollment_graduation_metrics", "auto"),
    (("مرافق",), "survey_student_facilities", "hybrid"),
    (("بنية", "تحتية"), "manual_infrastructure", "hybrid"),
    (("حوكمة",), "survey_faculty_dean", "evidence"),
    (("قيادة",), "survey_faculty_dean", "evidence"),
    (("مجلس",), "minutes_governance", "evidence"),
    (("جودة", "تحسين"), "quality_metrics_snapshot", "evidence"),
    (("تقييم", "أداء"), "survey_faculty_educational", "evidence"),
    (("طالب", "خدمات"), "survey_student_services", "evidence"),
    (("موظف",), "survey_staff_workplace", "evidence"),
]
